[[CURRENCIES]]
code="SEO"
issuer="GBQG54WA5HOYHEHJZK5H6PVFYGJPUEUCSGIPTJARY55MTWHHAC44QJ5S"
name="Tysseo7"
desc="This is a test token that is created as an example and has no value."
image="https://tysseo7.github.io/FUJI.jpg"
